New Nagios checks, some cassandra tweaks, and MongoDB stuff

diff --git a/cookbooks/authorization/files/default/postgres_monitor_daemon b/cookbooks/authorization/files/default/postgres_monitor_daemon
--- a/cookbooks/authorization/files/default/postgres_monitor_daemon
+++ b/cookbooks/authorization/files/default/postgres_monitor_daemon
@@ -2,57 +2,75 @@
 
 # This daemon will break heartbeat if the PostGres fails
 
+LOG=/var/log/ha-log
+
 POSTGRES=`which postgres`;
 
-. ~postgres/.bash_profile
-while true;
-do
+TMPLOG=/tmp/$$.psql.log
+rm -f $TMPLOG
 
+trap "rm -f $TMPLOG" EXIT
+
+. ~postgres/.bash_profile
+
+function test_connection
+{
   ps aux | grep postmaster | grep -v grep -q > /dev/null 2>&1;
   EC=$?;
 
   if [ "$EC" -eq "0" ]
   then
-    # Test connection
-    psql -d postgres -U postgres -c'select 1;' > /dev/null 2>&1;
 
+    psql -d postgres -U postgres -c'select 1;' > $TMPLOG 2>&1;
     EC=$?
-    if [ "$EC" -ne "0" ]
+
+    grep 'the database system is starting up' $TMPLOG > /dev/null 2>&1
+    RT=$?;
+
+    if [ "$EC" -ne "0" ] && [ "$RT" -ne "0" ]
     then
-
-      #attempt to restart postgres
-      /etc/init.d/postgres restart;
-      sleep 10; #give postgres time to start up
-
-      #test connection again
-      psql -d postgres -U postgres -c'select 1;' > /dev/null 2>&1
-      EC=$?
-
-      if [ "$EC" -ne "0" ]
-      then
-        /etc/init.d/heartbeat restart > /dev/null 2>&1; # restart heartbeat to force failover
-      fi;
-
-    fi;
+        ISRUNNING=2 # running unresponsive
+    else
+        ISRUNNING=1 # running healthy
+    fi
+  else
+    ISRUNNING=0 # not running
+  fi
+}
 
 
+while true;
+do
 
-  else # process is NOT running
+  test_connection;
+ 
+  if [ "$ISRUNNING" -eq "2" ] 
+  then
+  
+      echo "Server is not responding: attempting to restart postgres" | tee -a $LOG
+      /etc/init.d/postgres restart | tee -a $LOG;
+      echo "Sleeping 30 seconds" | tee -a $LOG
+      sleep 30; #give postgres time to start up
 
-    #attempt to restart postgres
-    /etc/init.d/postgres restart;
-    sleep 10; #give postgres time to start up
+      echo "Testing connection again" | tee -a $LOG
+      test_connection;
+  elif [ "$ISRUNNING" -eq "0" ]
+  then
+  
+      echo "Server is down: attempting to start postgres" | tee -a $LOG
+      /etc/init.d/postgres start | tee -a $LOG;
+      echo "Sleeping 30 seconds" | tee -a $LOG
+      sleep 30; #give postgres time to start up
 
-    #test again if postgres is running
-    ps aux | grep postmaster | grep -v grep -q > /dev/null 2>&1;
-    EC=$?;
+      echo "Testing connection again" | tee -a $LOG
+      test_connection;
+  fi
 
-    if [ "$EC" -ne "0" ]
-    then
-      /etc/init.d/heartbeat restart > /dev/null 2>&1; # restart heartbeat to force failover
-    fi;
-
-  fi;
+  if [ "$ISRUNNING" -eq "2" ] || [ "$ISRUNNING" -eq "0" ]
+  then
+      echo "Restarting heartbeat to force failover" | tee -a $LOG
+      /etc/init.d/heartbeat stop | tee -a $LOG; # stop heartbeat to force failover
+  fi  
 
   sleep 10;
 
