saving updates to work on something else

diff --git a/cookbooks/fac/templates/default/fac-incremental-runner.sh.erb b/cookbooks/fac/templates/default/fac-incremental-runner.sh.erb
--- a/cookbooks/fac/templates/default/fac-incremental-runner.sh.erb
+++ b/cookbooks/fac/templates/default/fac-incremental-runner.sh.erb
@@ -2,19 +2,37 @@
 
 SLEEP_MINUTES=20m
 
+EML_LIST=(<%= node.[:fac][:etl_notify].join " " %>)
+function onFail {
+	XVAL=$1;PTNM=$2;
+
+  echo "[$(date)] $0 : $(uname -n) ${PTNM} exited with nonzero status (${XVAL})" >&2;
+  # send email to everyone in the list
+  for i in $EML_LIST; do
+		mutt -s "$(uname -n) $0 abort report" $i < <(echo "[$(date)] $0 : ${PTNM} exited with nonzero status (${XVAL}) on host $(uname -n). Job was aborted");
+	done;
+	return 0;
+}
+
 /usr/bin/java -Xms4G -Xmx4G -jar <%= @script_dir %>/fac-music.jar classpath:/facStartup.xml trackIncremental time=$(date +%s) writeToMongo=true writeToAttivio=true jobType=trackIncremental reloadIds=8872138 doAmgMatch=true intervalOverride= independentJob=true commitSpeed=-1;
+[[ $? -ne 0 ]] && onFail ${?} "trackIncremental" && exit $?;
 
 sleep $SLEEP_MINUTES
 
 /usr/bin/java -Xms4G -Xmx4G -jar <%= @script_dir %>/fac-music.jar classpath:/facStartup.xml bundleIncremental time=$(date +%s) writeToMongo=true writeToAttivio=true jobType=bundleIncremental reloadIds=8872138 doAmgMatch=true intervalOverride= independentJob=false commitSpeed=-1;
-
+[[ $? -ne 0 ]] && onFail ${?} "bundleIncremental" && exit $?;
 
 /usr/bin/java -Xms4G -Xmx4G -jar <%= @script_dir %>/fac-music.jar classpath:/facStartup.xml artistIncremental time=$(date +%s) writeToMongo=true writeToAttivio=true jobType=artistIncremental reloadIds=8872138 doAmgMatch=true intervalOverride= independentJob=false commitSpeed=-1;
+[[ $? -ne 0 ]] && onFail ${?} "artistIncremental" && exit $?;
 
 /usr/bin/java -Xms4G -Xmx4G -jar <%= @script_dir %>/fac-music.jar classpath:/facStartup.xml artistIncrementalDelete time=$(date +%s) writeToMongo=true writeToAttivio=true jobType=artistIncrementalDelete reloadIds=8872138 doAmgMatch=true intervalOverride= independentJob=false commitSpeed=-1;
+[[ $? -ne 0 ]] && onFail ${?} "artistIncrementalDelete" && exit $?;
 
 /usr/bin/java -jar -Xmx14g <%= @radiobuild_dir %>/fac-radiobuild.jar
+[[ $? -ne 0 ]] && onFail ${?} "fac-radiobuild.jar@radiobuild_dir" && exit $?;
 
 /usr/bin/java -jar -Xmx14g <%= @radiobuild2_dir %>/fac-radiobuild.jar
+[[ $? -ne 0 ]] && onFail ${?} "fac-radiobuild.jar@radiobuild2_dir" && exit $?;
 
 /data/jobs/fac/music/shipFAC2attivio.sh
+[[ $? -ne 0 ]] && onFail ${?} "shipFAC2attivio.sh" && exit $?;
