updated max size in nginx conf

diff --git a/cookbooks/radioedit/templates/default/radioedit-initd.sh.erb b/cookbooks/radioedit/templates/default/radioedit-initd.sh.erb
--- a/cookbooks/radioedit/templates/default/radioedit-initd.sh.erb
+++ b/cookbooks/radioedit/templates/default/radioedit-initd.sh.erb
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 # #################################################
-# @FILE: 
+# chkconfig: 345 91 10 
+# @FILE: radioedit
 # @AUTHOR: GregoryPatmore <gregorypatmore@clearchannel.com>}
 # @CHEF-COOKBOOK: radioedit
 # @PROJECT: Radioedit Epona Launch
@@ -9,6 +10,7 @@
 # @SOFT-TABS: YES
 # @DESC: SystemV init.d script to manage the radioedit application server process.
 # @NOTES: 
+#
 # #################################################
 
 # Source function library.
@@ -18,7 +20,7 @@
 
 # Check that networking is up.
 if [ "${NETWORKING}" = "no" ]; then
-  error "**Error: $0 : Networking seems to be unavailable";
+  failure "**Error: $0 : Networking seems to be unavailable";
   # logger -s -p user.error "**Error: $0 : Networking seems to be unavailable";
   exit 1;
 fi
@@ -36,17 +38,17 @@ PIDFILE="<%= @pid_file %>";
 
 # # make sure we can execute on the supervisor daemon
 # [[ -x /etc/init.d/supervisor ]] \
-#   && error "**Error: $0 : Supervisor daemon service missing or not executable" \
+#   && failure "**Error: $0 : Supervisor daemon service missing or not executable" \
 #   && exit 1;
 
 # make sure we can execute the supervisorctl command
-[[ -x $SCTL ]] \
-  && error "**Error: $0 : Supervisor CTL command missing or not executable" \
+[[ ! -x $SCTL ]] \
+  && failure "**Error: $0 : Supervisor CTL command missing or not executable" \
   && exit 1;
 
 # make sure we got a pid file to write to.
 [[ -z "${PIDFILE}" ]] \
-  && error "**Error: $0 : No pid file path given" \
+  && failure "**Error: $0 : No pid file path given" \
   && exit 1;
 
 #@TODO: check that supervisor is running
@@ -54,12 +56,12 @@ PIDFILE="<%= @pid_file %>";
 # start the application withiin supervisor
 function start_app() {
   # source a setenv if one has been set
-  [[ -f $SETENV 2>/dev/null ]] \
+  [[ -f $SETENV ]] \
     && . $SETENV;
 
   result=$($SCTL start $APPNAME);
-  [[ $result -ne 0 ]] \
-    && error "**Error: $0 : Call to start application (${APPNAME}) exited with unclean status (${result})" \
+  [[ $? -ne 0 ]] \
+    && failure "**Error: $0 : Call to start application (${APPNAME}) exited with unclean status (${result})" \
     && exit 1;
 
   # @TODO: Register the pid file with sysv
@@ -68,14 +70,14 @@ function start_app() {
 # stop the application within supervisor
 function stop_app() {
   result=$($SCTL stop $APPNAME);
-  [[ $result -ne 0 ]] \
-    && error "**Error: $0 : Call to stop application (${APPNAME}) exited with unclean status (${result})" \
+  [[ $? -ne 0 ]] \
+    && failure "**Error: $0 : Call to stop application (${APPNAME}) exited with unclean status (${result})" \
     && exit 1;
 };
 
 # print the status of the app 
 function status_app() {
-  result=$($SCTL status $APPNAME | grep $APPNAME);
+  result=$( $SCTL status $APPNAME | grep "${APPNAME}" ) ;
   # if no results, the app is not running.
   [[ -z "${result}" ]] \
     && echo "${APPNAME} not running" \
@@ -102,9 +104,9 @@ case "$1" in
     ;;
 
   restart)
-    stop_app \
-      && sleep 5 \ 
-      && start_app;
+    stop_app;
+    sleep 5;
+    start_app;
     ;;
 
   status)
@@ -119,120 +121,3 @@ case "$1" in
 esac
 
 exit $?;
-
-
-
-
-
-
-
-
-
-
-
-
-# #!/bin/sh
-# #
-# # <daemonname> <summary>
-# #
-# # chkconfig:   <default runlevel(s)> <start> <stop>
-# # description: <description, split multiple lines with \
-# #              a backslash>
-
-# ### BEGIN INIT INFO
-# # Provides: 
-# # Required-Start: 
-# # Required-Stop: 
-# # Should-Start: 
-# # Should-Stop: 
-# # Default-Start: 
-# # Default-Stop: 
-# # Short-Description: 
-# # Description:      
-# ### END INIT INFO
-
-# # Source function library.
-# . /etc/rc.d/init.d/functions
-
-# exec="/path/to/<daemonname>"
-# prog="<service name>"
-# config="<path to major config file>"
-
-# [ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog
-
-# lockfile=/var/lock/subsys/$prog
-
-# start() {
-#     [ -x $exec ] || exit 5
-#     [ -f $config ] || exit 6
-#     echo -n $"Starting $prog: "
-#     # if not running, start it up here, usually something like "daemon $exec"
-#     retval=$?
-#     echo
-#     [ $retval -eq 0 ] && touch $lockfile
-#     return $retval
-# }
-
-# stop() {
-#     echo -n $"Stopping $prog: "
-#     # stop it here, often "killproc $prog"
-#     retval=$?
-#     echo
-#     [ $retval -eq 0 ] && rm -f $lockfile
-#     return $retval
-# }
-
-# restart() {
-#     stop
-#     start
-# }
-
-# reload() {
-#     restart
-# }
-
-# force_reload() {
-#     restart
-# }
-
-# rh_status() {
-#     # run checks to determine if the service is running or use generic status
-#     status $prog
-# }
-
-# rh_status_q() {
-#     rh_status >/dev/null 2>&1
-# }
-
-
-# case "$1" in
-#     start)
-#         rh_status_q && exit 0
-#         $1
-#         ;;
-#     stop)
-#         rh_status_q || exit 0
-#         $1
-#         ;;
-#     restart)
-#         $1
-#         ;;
-#     reload)
-#         rh_status_q || exit 7
-#         $1
-#         ;;
-#     force-reload)
-#         force_reload
-#         ;;
-#     status)
-#         rh_status
-#         ;;
-#     condrestart|try-restart)
-#         rh_status_q || exit 0
-#         restart
-#         ;;
-#     *)
-#         echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
-#         exit 2
-# esac
-# exit $?
